#!/bin/bash

DATA_ROOT=/home/ncos/ooo/EVIMO2/evimo_data_config/evimo2/


folders=(
./_failed_recordings/scene11_dyn_train_00
./_failed_recordings/scene11_dyn_train_03
./_failed_recordings/scene11_dyn_train_04
./_failed_recordings/scene7_01
./_failed_recordings/scene7_04
./_failed_recordings/scene8_02
./_failed_recordings/scene9_dyn_train_00
./_failed_recordings/scene9_dyn_train_04
./_failed_recordings/scene9_dyn_train_05
./_failed_recordings/sliding_2_08
./dark_imo/eval/scene16_d_dyn_test_01
./dark_imo/eval/scene16_d_dyn_test_04
./dark_imo/train/scene16_d_dyn_test_00
./dark_imo/train/scene16_d_dyn_test_02
./dark_imo/train/scene16_d_dyn_test_03
./dark_sanity/checkerboard_d_flat_fb
./dark_sfm/eval/scene17_d_01
./dark_sfm/eval/scene17_d_02
./dark_sfm/eval/static_objects_dark_00
./dark_sfm/train/scene17_d_00
./dark_sfm/train/scene17_d_03
./dark_sfm/train/scene17_d_04
./dark_sfm/train/static_objects_dark_01
./dark_sfm/train/static_objects_dark_02
./gaps_imo/eval/sliding_02
./gaps_imo/eval/sliding_2_00
./gaps_imo/eval/sliding_2_05
./gaps_imo/eval/sliding_2_06
./gaps_imo/eval/sliding_2_07
./gaps_imo/eval/sliding_car_02
./gaps_imo/train/dynamic_00
./gaps_imo/train/falling_objects_00
./gaps_imo/train/falling_objects_01
./gaps_imo/train/sliding_03
./gaps_imo/train/sliding_04
./gaps_imo/train/sliding_2_01
./gaps_imo/train/sliding_2_02
./gaps_imo/train/sliding_2_03
./gaps_imo/train/sliding_2_04
./gaps_imo/train/sliding_car_00
./gaps_imo/train/sliding_car_01
./gaps_sanity/checkerboard_flat_lr
./gaps_sanity/simple_depth_var_lr
./gaps_sanity/tabletop_flat_rot_z
./gaps_sfm/eval/simple_ego_0
./gaps_sfm/eval/static_objects_00
./gaps_sfm/train/simple_ego_1
./gaps_sfm/train/static_objects_02
./gaps_sfm/train/static_objects_03
./imo/eval/scene10_dyn_train_00
./imo/eval/scene13_dyn_test_00
./imo/eval/scene13_dyn_test_05
./imo/eval/scene14_dyn_test_03
./imo/eval/scene14_dyn_test_04
./imo/eval/scene14_dyn_test_05
./imo/eval/scene15_dyn_test_01
./imo/eval/scene9_dyn_train_02
./imo/train/scene10_dyn_train_01
./imo/train/scene10_dyn_train_02
./imo/train/scene10_dyn_train_03
./imo/train/scene10_dyn_train_04
./imo/train/scene11_dyn_train_01
./imo/train/scene11_dyn_train_02
./imo/train/scene12_dyn_test_00
./imo/train/scene12_dyn_test_01
./imo/train/scene13_dyn_test_01
./imo/train/scene13_dyn_test_02
./imo/train/scene13_dyn_test_03
./imo/train/scene14_dyn_test_00
./imo/train/scene14_dyn_test_01
./imo/train/scene14_dyn_test_02
./imo/train/scene15_dyn_test_00
./imo/train/scene15_dyn_test_03
./imo/train/scene15_dyn_test_06
./imo/train/scene6_dyn_train_00
./imo/train/scene6_dyn_train_01
./imo/train/scene6_dyn_train_02
./imo/train/scene6_dyn_train_03
./imo/train/scene9_dyn_train_01
./imo/train/scene9_dyn_train_03
./imo/train/scene9_dyn_train_06
./sanity/sliding_00
./sanity/sliding_01
./scene15_dyn_test_02
./scene15_dyn_test_04
./scene15_dyn_test_05
./sfm/eval/scene_03_00
./sfm/eval/scene_03_01
./sfm/eval/scene_03_02
./sfm/eval/scene_03_03
./sfm/eval/scene_03_04
./sfm/train/scene13_dyn_test_04
./sfm/train/scene7_00
./sfm/train/scene7_02
./sfm/train/scene7_03
./sfm/train/scene8_01
./sfm/train/scene8_03
./sfm/train/scene8_04
./sfm/train/scene_04_00
./sfm/train/scene_04_01
./sfm/train/scene_04_02
./sfm/train/scene_04_03
./sfm/train/scene_04_04
./sfm/train/scene_05_00
./sfm/train/scene_05_01
./sfm/train/scene_05_02
./sfm/train/scene_05_03
./sfm/train/scene_05_04
./sfm/train/seq_1_0
./sfm/train/seq_1_1
./sfm/train/seq_1_2
./sfm/train/seq_1_3
./sfm/train/seq_1_4
./sfm/train/seq_1_5
./sfm/train/seq_2_1
./sfm/train/seq_2_2
./sfm/train/seq_2_3
./sfm/train/seq_2_4
./sfm/train/seq_2_5
./sfm/train/static_objects_01
)


for folder in "${folders[@]}"
do
    dataset_folder=$DATA_ROOT/$folder
    echo $dataset_folder

    bash ./generate.sh $dataset_folder
done
